# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Group14Alpha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Group14Alpha

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'SpotifyKit', '~> 0.0'
pod 'Alamofire', '~> 4.5'
end
