# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Group14Alpha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Group14Alpha

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

end
